apiVersion: v1
kind: Pod
metadata:
  name: exec-webhook-test-pod
  labels:
    app: exec-webhook
    controller.devfile.io/creator: "yesd"
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]